/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prefingermatch;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author USUARIO
 */
public class MainFrame extends javax.swing.JFrame {

    private BufferedImage mImage;
    private int xAnterior = 0, xActual = 1;
    private int yAnterior = 0, yActual = 1;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jLabel1);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Procesar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Abrir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 167, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGE FILES (*.bmp, *.gif, *.jpg, *.jpeg, *.png, *.tif)", "bmp", "gif", "jpg", "jpeg", "png", "tif");
        jFileChooser1.setFileFilter(filter);
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            System.out.println(file);
            try {
                mImage = ImageIO.read(file);
                System.out.println(mImage);
                jLabel1.setIcon(new ImageIcon(mImage));
            } catch (IOException e) {
                System.out.println(e);
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Hay que mandar a blanco cualquier cosa que no sea negro
        /*for (int x = 0; x < mImage.getWidth(); x++) {
            for (int y = 0; y < mImage.getHeight(); y++) {
                Color color = new Color(mImage.getRGB(x, y));
                if (color.getRGB() != Color.BLACK.getRGB() && color.getRed() > 20) {
                    mImage.setRGB(x, y, Color.WHITE.getRGB());
                } else {
                    mImage.setRGB(x, y, Color.BLACK.getRGB());
                }
            }
        }*/

        c:
        for (int x = 1; x < mImage.getWidth() - 1; x += 3) {
            for (int y = 1; y < mImage.getHeight() - 1; y += 3) {
                Color color = new Color(mImage.getRGB(x, y));
                if (color.getRGB() == Color.BLACK.getRGB()) {
                    //if (xActual < (mImage.getWidth() - 2) && yActual < (mImage.getHeight() - 2)) {
                    BufferedImage subimagen = mImage.getSubimage(x - 1, y - 1, 3, 3);
                    System.out.println("X " + (x - 1) + " Y " + (y - 1));
                    //Extractor ext = new Extractor(subimagen);
                    //ext.setVisible(true);
                    long c = 0;
                    int countPixels = 0;
                    List<Integer> pixelValues = new ArrayList<>();
                    pixelValues.add(new Color(subimagen.getRGB(0, 0)).getRGB() == Color.BLACK.getRGB() ? 0 : 1);
                    pixelValues.add(new Color(subimagen.getRGB(0, 1)).getRGB() == Color.BLACK.getRGB() ? 0 : 1);
                    pixelValues.add(new Color(subimagen.getRGB(0, 2)).getRGB() == Color.BLACK.getRGB() ? 0 : 1);
                    pixelValues.add(new Color(subimagen.getRGB(1, 2)).getRGB() == Color.BLACK.getRGB() ? 0 : 1);
                    pixelValues.add(new Color(subimagen.getRGB(2, 2)).getRGB() == Color.BLACK.getRGB() ? 0 : 1);
                    pixelValues.add(new Color(subimagen.getRGB(2, 1)).getRGB() == Color.BLACK.getRGB() ? 0 : 1);
                    pixelValues.add(new Color(subimagen.getRGB(2, 0)).getRGB() == Color.BLACK.getRGB() ? 0 : 1);
                    pixelValues.add(new Color(subimagen.getRGB(1, 0)).getRGB() == Color.BLACK.getRGB() ? 0 : 1);
                    for (int i = 1; i < 9; i++) {
                        c += Math.abs(pixelValues.get(i % 8) - pixelValues.get(i - 1));
                        countPixels += pixelValues.get(i - 1);
                    }
                    System.out.println("c " + c);
                    c /= 2.0;
                    System.out.println("c " + c);
                    String tipoImagen;
                    if (c == 1) {
                        if (countPixels == 7) {
                            tipoImagen = "tipo 1";
                        } else {
                            tipoImagen = "tipo 2";
                        }
                    } else if (c == 2) {
                        tipoImagen = "tipo 2";
                    } else {
                        tipoImagen = "tipo 3";
                    }
                    File file = new File(System.getProperty("user.dir") + "/archivos/" + tipoImagen + "/" + System.currentTimeMillis() + ".png");
                    try {
                        ImageIO.write(subimagen, "png", file);
                    } catch (IOException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    xActual = x;
                    yActual = y;
                    //}
                    //yActual+=5;
                    //break c;
                }
            }
        }

        /*mImage = new ThinningAlgorithm(mImage).thinImage();
        jLabel1.setIcon(new ImageIcon(mImage));*/

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int action = jFileChooser1.showSaveDialog(null);
            if (action != JFileChooser.APPROVE_OPTION) {
                return;
            }
            File file = jFileChooser1.getSelectedFile();
            ImageIO.write(mImage, "png", file);
            JOptionPane.showMessageDialog(this, "Imagen guardada correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
